language: node_js
sudo: false
node_js:
- '10'
- '8'
- '6'
- '4'
script: npm test
jobs:
  include:
  - stage: npm release
    node_js: '10'
    deploy:
      provider: npm
      email: jwhitlock@apache.org
      api_key:
        secure: <your-secure-key>
    if: branch = master